services:
  pgdb:
    image: postgres:alpine
    volumes:
      - sqpostgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass123}
      POSTGRES_DB: ${POSTGRES_DB:-booking}
      TZ: Europe/Sofia
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - sqpgadmindata:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL:-example@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD:-pass123}
      TZ: Europe/Sofia
    ports:
        - "5050:80"
  
volumes:
  sqpostgresdata:
  sqpgadmindata:
